version: '3.8'
services:
  generator_stable_diffusion:
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data:/app/data:rw
    build: generator_stable_diffusion
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=Europe/Moscow
      - HUGGINGFACE_USE_AUTH_TOKEN=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
